server:
  port: 8081

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

logging:
  level:
    org.springframework.security: DEBUG

